# http://travis-ci.org configuration file
language: cpp

compiler:
  - gcc
  - clang:

sudo: false

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - g++-4.8
      - lcov

env:
  global:
    - BUILD_RELEASE=${TRAVIS_BUILD_DIR}/build

before_install:
 - gem install coveralls-lcov

before_script:
  - export CXX="g++-4.8"
  # Create build folder
  - mkdir $BUILD_RELEASE
  # Release build
  - cd $BUILD_RELEASE && cmake -DCMAKE_BUILD_TYPE=release ..

script:
  - cd $BUILD_RELEASE && make check

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  # If GCC: compute code coverage and export it to coveralls
  - if [ "$CC" = "gcc" ];
    then
      lcov --capture --directory $BUILD_RELEASE --base-directory=${TRAVIS_BUILD_DIR}--output-file=coverage.info;
      lcov --extract coverage.info "*/ImplicitelySharedData/include/*" --output-file=coverage.info;
      coveralls-lcov coverage.info;
    fi

