# http://travis-ci.org configuration file
language: cpp

compiler:
  - gcc
  - clang:

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-4.8

env:
  global:
    - SOURCE=${TRAVIS_BUILD_DIR}/src
    - BUILD=${TRAVIS_BUILD_DIR}/build

before_script:
  - export CXX="g++-4.8"
  # Create build folder
  - mkdir build_release
  # Release build
  - cd build_release && cmake -DCMAKE_BUILD_TYPE=release ..

script:
  - cd build_release && make check


