# http://travis-ci.org configuration file
language: cpp

compiler:
  - gcc
  - clang:

sudo: false

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - gcc-4.8
      - g++-4.8
      - lcov

env:
  global:
    - BUILD_RELEASE=${TRAVIS_BUILD_DIR}/build
    - BUILD_COVERAGE=${TRAVIS_BUILD_DIR}/coverage

before_install:
 - gem install coveralls-lcov

before_script:
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"
  - export GCOV="gcov-4.8"
  # Create build folder
  - mkdir $BUILD_RELEASE
  # Release build
  - cd $BUILD_RELEASE && cmake -DCMAKE_BUILD_TYPE=release ..

script:
  - cd $BUILD_RELEASE && make check

after_success:
  # If GCC: compute code coverage and export it to coveralls
  - if [ "$CC" = "gcc-4.8" ];
    then
      mkdir $BUILD_COVERAGE;
      cd $BUILD_COVERAGE;
      cmake ${TRAVIS_BUILD_DIR} -DBUILD_COVERAGE=ON;
      make check;
      lcov --debug --gcov-tool /usr/bin/gcov-4.8 --capture --directory $BUILD_COVERAGE --base-directory=${TRAVIS_BUILD_DIR} --output-file=coverage.info;
      lcov --extract coverage.info "*/ImplicitelySharedData/include/*" --output-file=coverage.info;
      coveralls-lcov coverage.info;
    fi

