version: 1.0.{build}

environment:
  WORK_DIR: "c:\dev\"
  matrix:
    - GENERATOR: "Visual Studio 14 2015 Win64"
    - GENERATOR: "Visual Studio 14 2015"
    
clone_folder: %WORK_DIR%\src

build_script:
  - cd %WORK_DIR%
  - mkdir build
  - cd build
  - cmake -G"%GENERATOR%" ../src
  - cmake --build . --config Release --target check

build:
  parallel: true
  verbosity: minimal

